name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Adjust to your Node.js version

      # Step 3: Create SSH key
      - name: Create SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > private_key.pem
          chmod 400 private_key.pem

      # Step 4: Install rsync
      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      # Step 5: Copy files to EC2
      - name: Copy files to EC2
        run: |
          rsync -av -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" \
            --progress . ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/my-node-app \
            --exclude node_modules
          rsync -av -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" \
            ./nginx/my-node-app.conf ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/nginx/

      # Step 6: Deploy and configure on EC2
      - name: Deploy to EC2
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            # Update system packages
            sudo apt update && sudo apt upgrade -y

            # Create directories
            mkdir -p /home/ubuntu/my-node-app
            mkdir -p /home/ubuntu/nginx

            # Navigate to app directory
            cd /home/ubuntu/my-node-app

            # Install dependencies
            npm install

            # Install PM2 globally with sudo
            sudo npm install -g pm2

            # Stop any existing PM2 process
            pm2 delete my-node-app || true

            # Start the application
            pm2 start index.js --name my-node-app
            pm2 save

            # Copy Nginx configuration
            sudo mkdir -p /etc/nginx/sites-available
            sudo mkdir -p /etc/nginx/sites-enabled
            sudo cp /home/ubuntu/nginx/my-node-app.conf /etc/nginx/sites-available/my-node-app.conf
            sudo ln -sf /etc/nginx/sites-available/my-node-app.conf /etc/nginx/sites-enabled/my-node-app.conf

            # Test and reload Nginx
            sudo nginx -t
            sudo systemctl reload nginx
          EOF

      # Step 7: Clean up SSH key
      - name: Clean up
        run: rm -f private_key.pem
