name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Adjust to your Node.js version

    # Step 3: Create SSH key file
    - name: Create SSH key
      run: |
        echo "${{ secrets.EC2_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    # Step 4: Install dependencies locally (optional, for validation)
    - name: Install dependencies
      run: npm install

    # Step 5: Transfer files to EC2
    - name: Transfer files to EC2
      run: |
        rsync -avz -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" \
          ./index.js ./package.json ./package-lock.json \
          ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/my-node-app/

    # Step 6: Deploy to EC2
    - name: Deploy to EC2
      run: |
        ssh -T -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          # Update system packages
          sudo apt update -y
          sudo apt upgrade -y

          # Install Node.js and npm if not already installed
          sudo apt install -y nodejs npm

          # Create app directory with correct permissions
          sudo mkdir -p /home/ubuntu/my-node-app
          sudo chown ubuntu:ubuntu /home/ubuntu/my-node-app

          # Install app dependencies
          cd /home/ubuntu/my-node-app
          npm install
          npm install pm2 --save # Install PM2 locally

          # Stop any existing PM2 processes
          ./node_modules/.bin/pm2 delete all || true

          # Start app with PM2
          ./node_modules/.bin/pm2 start index.js --name my-node-app
          ./node_modules/.bin/pm2 save

          # Install and configure Nginx
          sudo apt install -y nginx
          sudo mkdir -p /home/ubuntu/nginx
          cat <<EOT | sudo tee /home/ubuntu/nginx/my-node-app.conf
server {
    listen 80;
    server_name ${{ secrets.EC2_HOST }};
    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_cache_bypass \$http_upgrade;
    }
}
EOT
          # Copy Nginx config to sites-available and enable it
          sudo cp /home/ubuntu/nginx/my-node-app.conf /etc/nginx/sites-available/my-node-app.conf
          sudo ln -sf /etc/nginx/sites-available/my-node-app.conf /etc/nginx/sites-enabled/my-node-app.conf

          # Remove default Nginx site if exists
          sudo rm -f /etc/nginx/sites-enabled/default

          # Test and restart Nginx
          sudo nginx -t
          sudo systemctl restart nginx
          sudo systemctl enable nginx
        EOF

    # Step 7: Clean up SSH key
    - name: Clean up
      run: rm -f private_key.pem
